#!/bin/bash
export GIT_COMMITTER_DATE="Wed Feb 21 19:01 2020 +0100"
   export GIT_AUTHOR_DATE="Wed Feb 21 05:09 2020 +0100"
git add .
git commit -am " new update to code scripts"
git push origin master

