- name: Copy the sonar files required
  copy:
    src: sonar-postress-template.yaml
    dest: /tmp

- name: Copy the nexus files required
  copy:
    src: nexus-template.yaml
    dest: /tmp


- name: Login into Openshift

  shell: ~/oc_CLI/oc login -u {{ user }} {{ oshost }}
  shell: "~/oc_CLI/oc new-project {{ project }}" 

- name: Create the Nexus Instance
  shell: "~/oc_CLI/oc new-app -n {{ project }}  -f /tmp/nexus-template.yaml"

- name: Create the Sonarqube Instance
  shell: "~/oc_CLI/oc new-app -n {{ project }}  -f /tmp/sonar-postress-template.yaml --param=SONARQUBE_VERSION=6.7"

- name: Create the Jenkins Instance
  shell: "oc new-app -n {{ project }} jenkins-ephemeral"
