- name: Copy Java Template File
  copy:
    src: configmapTemplate.yml
    dest: /tmp

- name: Create the pipeline
  shell: oc process -f /tmp/configmapTemplate.yml -p APPLICATION_NAME={{ app }} -p PIPELINE_NAME={{ pipeline_name }} -p GIT_URL={{ gitrepo }} -p GIT_TOKEN={{ gittoken }} -p CONFIGMAPFILE_NAME={{ configmapfilename }} CONFIGMAPFILE_PATH={{ configmapfilepath }} CONFIGMAP_NAME={{ configmapname }} -p DEV_PROJECT={{ appproject_dev }} | oc create -f-

- name: Start the build
  shell: "oc start-build {{ pipeline_name }}"


